version: 2
updates:

  # ================================
  # GitHub Actions
  # ================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    assignees:
      - "EstrogenHRT"
    labels:
      - "Dependabot"
    open-pull-requests-limit: 99

  # ================================
  # CDN
  # ================================
  - package-ecosystem: "npm"
    directory: "/win/cdn"
    schedule:
      interval: "daily"
      time: "09:45"
    assignees:
      - "Doughmination"
    labels:
      - "Dependabot"
      - "Python"
    open-pull-requests-limit: 99

  # ================================
  # Doughmination System Backend
  # ================================
  - package-ecosystem: "pip"
    directory: "/win/system/backend"
    schedule:
      interval: "daily"
      time: "09:45"
    assignees:
      - "Doughmination"
    labels:
      - "Dependabot"
      - "Python"
    open-pull-requests-limit: 99

  # ================================
  # Doughmination System Frontend (React)
  # ================================
  - package-ecosystem: "npm"
    directory: "/win/system/frontend"
    schedule:
      interval: "daily"
      time: "09:45"
    assignees:
      - "Doughmination"
    labels:
      - "Dependabot"
      - "JavaScript"
    open-pull-requests-limit: 99
