# Most updated version of Dependabot
version: 2
updates:

# ================================
# GitHub Actions
# ================================

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "08:00"
    assignees:
      - "EstrogenHRT"
    labels:
      - "Dependabot"
    open-pull-requests-limit: 99

# ================================
# Yuri Lover Files Website
# ================================

  - package-ecosystem: "pip"
    directory: "yuri-lover.win"
    schedule:
      interval: "daily"
      time: "09:45"
    assignees:
      - "EstrogenHRT"
    labels:
      - "Dependabot"
      - "Python"
    open-pull-requests-limit: 99
