services:
  discord:
    image: ghcr.io/the-snesler/discord-github-preview:latest
    container_name: discord
    ports:
      - "8002:3000"
    env_file: .env.discord
    restart: unless-stopped
  dough-back:
    image: clovetwilight3/doughmination-backend:latest
    container_name: dough-back
    ports:
      - "8000:8000"
    volumes:
      - "./dough-data:/app/dough-data"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.envkeys:ro"
    restart: unless-stopped
  dough-front:
    image: clovetwilight3/doughmination-frontend:latest
    container_name: dough-front
    ports:
      - "8001:8001"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.envkeys:ro"
    depends_on:
      - dough-back
  yuri:
    build:
      context: ./yuri-lover.win
      dockerfile: Dockerfile
    container_name: yuri-cdn
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./yuri-lover.win/root:/app/root"
      - "./yuri-lover.win/cdn:/app/cdn"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.envkeys:ro"
    restart: unless-stopped
volumes:
  backend_data:
  backend_avatars:
  
