services:
#  discord:
#    image: ghcr.io/the-snesler/discord-github-preview:latest
#    container_name: discord
#    ports:
#      - "8002:3000"
#    env_file: .env.discord
#    restart: unless-stopped
  dough-back:
    build:
      context: ./system/backend
      dockerfile: Dockerfile
    container_name: dough-back
    ports:
      - "8000:8000"
    volumes:
      - "./dough-data:/app/dough-data"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped
  dough-front:
    build:
      context: ./system/frontend
      dockerfile: Dockerfile
    container_name: dough-front
    ports:
      - "8001:8001"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    depends_on:
      - dough-back
  cdn:
    build:
      context: ./cdn
      dockerfile: Dockerfile
    container_name: yuri-cdn
    ports:
      - "8080:8080"
    volumes:
      - "./cdn/root:/app/root"
      - "./cdn/cdn:/app/cdn"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped
volumes:
  backend_data:
  backend_avatars:
  
