services:
  dough-back:
    image: clovetwilight3/doughmination-backend:latest
    container_name: dough-back
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./dough-data:/app/dough-data"
    restart: unless-stopped
  dough-front:
    image: clovetwilight3/doughmination-frontend:latest
    container_name: dough-front
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - dough-back
  yuri:
    build:
      context: ./yuri-lover.win
      dockerfile: Dockerfile
    container_name: yuri-cdn
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./yuri-lover.win/root:/app/root
      - ./yuri-lover.win/cdn:/app/cdn
    restart: unless-stopped
volumes:
  backend_data:
  backend_avatars:
  
