services:
  dough-back:
    build:
      context: ./win/system/backend
      dockerfile: Dockerfile
    container_name: dough-back
    ports:
      - "8000:8000"
    volumes:
      - "./dough-data:/app/dough-data"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped
  dough-front:
    build:
      context: ./win/system/frontend
      dockerfile: Dockerfile
    container_name: dough-front
    ports:
      - "8001:8001"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    depends_on:
      - dough-back
  cdn:
    build:
      context: ./win/cdn
      dockerfile: Dockerfile
    container_name: cdn
    ports:
      - "8080:8080"
    volumes:
      - "./cdn/cdn:/app/cdn"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped
volumes:
  backend_data:
  backend_avatars:
  
