# Copyright (c) 2026 Clove Twilight
# Licensed under the ESAL-1.3 Licence.
# See LICENCE.md in the project root for full licence information.
services:

  company:
    build:
      context: ./win/root
      dockerfile: Dockerfile
    container_name: company
    ports:
      - "127.0.0.1:8003:8003"
    restart: always

  modding:
    image: clovetwilight3/doughmination-modding
    ports:
      - "127.0.0.1:8002:8002"
    container_name: modding
    restart: unless-stopped

  dough-back:
    build:
      context: ./co/system/backend
      dockerfile: Dockerfile
    container_name: dough-back
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./dough-data:/app/dough-data"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped

  dough-front:
    build:
      context: ./co/system/frontend
      dockerfile: Dockerfile
    container_name: dough-front
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    depends_on:
      - dough-back

  cdn:
    build:
      context: ./win/cdn
      dockerfile: Dockerfile
    container_name: cdn
    environment:
      - NODE_ENV=development
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./win/cdn/cdn:/app/cdn"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped

volumes:
  backend_data:
  backend_avatars:
  
